create table STG_LE_RISK_OWNER
(
  LE_DOMAIN            VARCHAR2(255),
  LE_VERSION           NUMBER(20),
  LE_ID                NUMBER(20),
  LEGAL_NAME           VARCHAR2(255),
  RISK_OWNER_TYPE      VARCHAR2(255),
  RISK_OWNER_ROLE      VARCHAR2(255),
  RISK_OWNER_CODE      VARCHAR2(255),
  RISK_OWNER_DESC      VARCHAR2(255),
  PRIMARY_CONTACT      VARCHAR2(255),
  OWNING_GROUP_CODE    VARCHAR2(255),
  STG_EFFECTIVE_DATE   DATE,
  STG_LOAD_DATE        DATE,
  STG_LOAD_ID          NUMBER(20),
  STG_JOB_RUN_ID       NUMBER(20)
);
