create table STG_LE_CONTR_ENTITY
(
  LE_DOMAIN              VARCHAR2(255),
  LE_VERSION             NUMBER(20),
  LE_ID                  NUMBER(20),
  LEGAL_NAME             VARCHAR2(255),
  CONTR_ENTITY_ID        NUMBER(20),
  CONTR_ENTITY_DOMAIN    VARCHAR2(255),
  CONTR_ENTITY_NAME      VARCHAR2(255),
  CONTR_ENTITY_UPDT_DATE DATE,
  CONTR_ENTITY_STATUS    VARCHAR2(50),
  STG_EFFECTIVE_DATE     DATE,
  STG_LOAD_DATE          DATE,
  STG_LOAD_ID            NUMBER(20),
  STG_JOB_RUN_ID         NUMBER(20)
);
