create table STG_TA_RELATIONSHIP
(
  TRADING_ACC_NK           VARCHAR2(255),
  TRADING_ACC_DOMAIN       VARCHAR2(255),
  TRADING_ACC_VERSION      NUMBER(20),
  TRADING_ACC_ID           NUMBER(10),
  RELATIONSHIP_ID          VARCHAR2(255),
  RELATIONSHIP_DOMAIN      VARCHAR2(255),
  RELATIONSHIP_TYPE        VARCHAR2(255),
  RELATIONSHIP_STATUS_DATE DATE,
  RELATIONSHIP_STATUS      VARCHAR2(50),
  STG_EFFECTIVE_DATE       DATE,
  STG_LOAD_DATE            DATE,
  STG_LOAD_ID              NUMBER(20),
  STG_JOB_RUN_ID           NUMBER(20)
);
