Given a 5 by 5 game
When I toggle the cell at (2, 3)
Then the grid should look like
.....
.....
.....
..X..
.....
When I toggle the cell at (2, 4)
Then the grid should look like
.....
.....
.....
..X..
..X..
When I toggle the cell at (2, 3)
Then the grid should look like
.....
.....
.....
.....
..X..

Given a 6 by 2 game
When I toggle the cell at (0, 0)
Then the grid should look like
X.....
......
When I toggle the cell at (1, 1)
Then the grid should look like
X.....
.X....
When I toggle the cell at (0, 0)
Then the grid should look like
......
.X....
When I toggle the cell at (1, 1)
Then the grid should look like
......
......
When I toggle the cell at (4, 0)
Then the grid should look like
....X.
......
When I toggle the cell at (2, 1)
Then the grid should look like
....X.
..X...